### ISSUE TITLE
Coordinate system error

### ISSUE THREAD

**Issue by Jean-Romain** [r-lidar/lidR#586]
### Discussed in https://github.com/r-lidar/lidR/discussions/585

<div type='discussions-op-text'>

<sup>Originally posted by **Phome95** May 21, 2022</sup>
Hello, I am attempting to use the silva2016 algorithm:

```r
library(lidR)
library(raster)
chm <- raster("chm_clean2.tif")
ttops <- locate_trees(chm, lmf(3))
crowns <- silva2016(chm, ttops)()
```

however this error comes up:

```
Error in geos_op2_geom("intersection", x, y, ...) : 
  st_crs(x) == st_crs(y) is not TRUE
```

However both coordinate systems are the same.

:link: [download data](https://drive.google.com/file/d/1pzQ3crlBwp3LS-vvqoPef8V_io1W-Iq5/view?usp=sharing)
</div>

**Comment by Jean-Romain** [comment]
I get 

```
Erreur : Large on-disk rasters are not supported by locate_tree. Load the raster manually.
```

which is the expected error

**Comment by Jean-Romain** [comment]
Fixed

**Comment by Phome95** [comment]
![image](https://user-images.githubusercontent.com/100789966/170265703-119410f7-6eb1-43c4-8f18-90b2911cf379.png)
Hi, I am still receiving the same error message?

**Comment by Jean-Romain** [comment]
Have you updated lidR?

**Comment by Phome95** [comment]
yes, version 4.0.0

**Comment by Jean-Romain** [comment]
Version 4.0.0 is the one that have a bug. Latest version on CRAN is 4.0.1. Your bug has been fixed in 4.0.2 available here on github.

**Comment by Phome95** [comment]
In the release section?

**Comment by Phome95** [comment]
It worked thank you!
